name: Deploy to GitHub Pages

on:
  push:
<<<<<<< Updated upstream
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

=======
    branches: [ main ]
  workflow_dispatch:

>>>>>>> Stashed changes
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
<<<<<<< Updated upstream
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Setup Node.js âš™ï¸
=======
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
>>>>>>> Stashed changes
        uses: actions/setup-node@v3
        with:
          node-version: 18

<<<<<<< Updated upstream
      - name: Install dependencies ðŸ“¦
        run: npm ci

      - name: Build ðŸ—ï¸
        run: npm run build

      - name: Deploy to GitHub Pages ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Output directory
          branch: gh-pages
=======
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # VÃ½stupnÃ­ adresÃ¡Å™ vaÅ¡eho buildu
>>>>>>> Stashed changes
